# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50624b14d6abbf69985fa94a1872fc3f37ff792f834fd00b4e9b5fe57ade2cf9babafed819a9ec5cf04d54a8e0cac6ef7d36cddb972b98f09be3a6cd8a4c7bec

test:
  secret_key_base: 9a39ffd5520bd39742f222fa4665af133e4a2517c306042e346dda36cd956b29cb035363941fbc310e2692cf035ea1fb1f4debc385fb79c744ac513c922146e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
